baseURL: "https://gaconnoone99.github.io"
languageCode: "en-us"
title: "Frenda-profile"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Duong Xuan Manh"
  profession: "QA Engineer"
  github: "https://github.com/gaconnoone99/"
  linkedin: "https://www.linkedin.com/in/frenda-malaka-675a8221a/"
  twitter: "https://twitter.com/yuukifrenda"
  instagram: "https://www.instagram.com/d.x.manh/"
  facebook: "https://www.facebook.com/gaconoone99/"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Profile, a passionate web developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"
  skills:
    - name: QA/AC testing
      percentage: 85
    - name: Information security
      percentage: 60
    - name: Web Dev
      percentage: 60
    - name: Embedded System
      percentage: 50

  # Experience
  disable_experience: false
  experience:
    - company: "OPSWAT"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Associate QA engineer"
      startdate: Aug 2021
      enddate: present
      featuredpoints:
        - point: Check functionality and quality of security software products (Metadefender Core).
        - point: Improving software development processes.
    - company: CNSC"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Internship tester"
      startdate: Mar 2021
      enddate: Jul 2021
      featuredpoints:
        - point: Learn the basics of QA and website security.
        - point: Test the functionality of websites on PC devices.
    - company: "Testio/Utest"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Freelance Tester"
      startdate: Mar 2021
      enddate: present
      featuredpoints:
        - point: Test the functionality of websites on mobile devices.
        - point: Test the functionality of websites on PC devices.

  # Education
  disable_education: false
  education:
    - degree: "Security engineering"
      branch: "Information Technology"
      university: "University of Information Technology"
      startedyear: "2017"
      graduation: "2021"
    - degree: "Degree"
      branch: "Physics"
      university: "Vinh University's specialized school"
      startedyear: "2014"
      graduation: "2017"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "gaconnoone1999@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
